// automatically generated by the FlatBuffers compiler, do not modify
// @generated

extern crate alloc;

#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MIN_OPCODE: u8 = 0;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MAX_OPCODE: u8 = 10;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
#[allow(non_camel_case_types)]
pub const ENUM_VALUES_OPCODE: [Opcode; 11] = [
  Opcode::Input,
  Opcode::Call,
  Opcode::Calc,
  Opcode::Decide,
  Opcode::Switch,
  Opcode::Act,
  Opcode::Parallel,
  Opcode::Loop,
  Opcode::Wait,
  Opcode::Merge,
  Opcode::Error,
];

#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Default)]
#[repr(transparent)]
pub struct Opcode(pub u8);
#[allow(non_upper_case_globals)]
impl Opcode {
  pub const Input: Self = Self(0);
  pub const Call: Self = Self(1);
  pub const Calc: Self = Self(2);
  pub const Decide: Self = Self(3);
  pub const Switch: Self = Self(4);
  pub const Act: Self = Self(5);
  pub const Parallel: Self = Self(6);
  pub const Loop: Self = Self(7);
  pub const Wait: Self = Self(8);
  pub const Merge: Self = Self(9);
  pub const Error: Self = Self(10);

  pub const ENUM_MIN: u8 = 0;
  pub const ENUM_MAX: u8 = 10;
  pub const ENUM_VALUES: &'static [Self] = &[
    Self::Input,
    Self::Call,
    Self::Calc,
    Self::Decide,
    Self::Switch,
    Self::Act,
    Self::Parallel,
    Self::Loop,
    Self::Wait,
    Self::Merge,
    Self::Error,
  ];
  /// Returns the variant's name or "" if unknown.
  pub fn variant_name(self) -> Option<&'static str> {
    match self {
      Self::Input => Some("Input"),
      Self::Call => Some("Call"),
      Self::Calc => Some("Calc"),
      Self::Decide => Some("Decide"),
      Self::Switch => Some("Switch"),
      Self::Act => Some("Act"),
      Self::Parallel => Some("Parallel"),
      Self::Loop => Some("Loop"),
      Self::Wait => Some("Wait"),
      Self::Merge => Some("Merge"),
      Self::Error => Some("Error"),
      _ => None,
    }
  }
}
impl ::core::fmt::Debug for Opcode {
  fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
    if let Some(name) = self.variant_name() {
      f.write_str(name)
    } else {
      f.write_fmt(format_args!("<UNKNOWN {:?}>", self.0))
    }
  }
}
impl<'a> ::flatbuffers::Follow<'a> for Opcode {
  type Inner = Self;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    let b = unsafe { ::flatbuffers::read_scalar_at::<u8>(buf, loc) };
    Self(b)
  }
}

impl ::flatbuffers::Push for Opcode {
    type Output = Opcode;
    #[inline]
    unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
        unsafe { ::flatbuffers::emplace_scalar::<u8>(dst, self.0) };
    }
}

impl ::flatbuffers::EndianScalar for Opcode {
  type Scalar = u8;
  #[inline]
  fn to_little_endian(self) -> u8 {
    self.0.to_le()
  }
  #[inline]
  #[allow(clippy::wrong_self_convention)]
  fn from_little_endian(v: u8) -> Self {
    let b = u8::from_le(v);
    Self(b)
  }
}

impl<'a> ::flatbuffers::Verifiable for Opcode {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    u8::run_verifier(v, pos)
  }
}

impl ::flatbuffers::SimpleToVerifyInSlice for Opcode {}
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MIN_EDGE_KIND: u8 = 0;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MAX_EDGE_KIND: u8 = 1;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
#[allow(non_camel_case_types)]
pub const ENUM_VALUES_EDGE_KIND: [EdgeKind; 2] = [
  EdgeKind::EK_Data,
  EdgeKind::EK_Control,
];

#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Default)]
#[repr(transparent)]
pub struct EdgeKind(pub u8);
#[allow(non_upper_case_globals)]
impl EdgeKind {
  pub const EK_Data: Self = Self(0);
  pub const EK_Control: Self = Self(1);

  pub const ENUM_MIN: u8 = 0;
  pub const ENUM_MAX: u8 = 1;
  pub const ENUM_VALUES: &'static [Self] = &[
    Self::EK_Data,
    Self::EK_Control,
  ];
  /// Returns the variant's name or "" if unknown.
  pub fn variant_name(self) -> Option<&'static str> {
    match self {
      Self::EK_Data => Some("EK_Data"),
      Self::EK_Control => Some("EK_Control"),
      _ => None,
    }
  }
}
impl ::core::fmt::Debug for EdgeKind {
  fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
    if let Some(name) = self.variant_name() {
      f.write_str(name)
    } else {
      f.write_fmt(format_args!("<UNKNOWN {:?}>", self.0))
    }
  }
}
impl<'a> ::flatbuffers::Follow<'a> for EdgeKind {
  type Inner = Self;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    let b = unsafe { ::flatbuffers::read_scalar_at::<u8>(buf, loc) };
    Self(b)
  }
}

impl ::flatbuffers::Push for EdgeKind {
    type Output = EdgeKind;
    #[inline]
    unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
        unsafe { ::flatbuffers::emplace_scalar::<u8>(dst, self.0) };
    }
}

impl ::flatbuffers::EndianScalar for EdgeKind {
  type Scalar = u8;
  #[inline]
  fn to_little_endian(self) -> u8 {
    self.0.to_le()
  }
  #[inline]
  #[allow(clippy::wrong_self_convention)]
  fn from_little_endian(v: u8) -> Self {
    let b = u8::from_le(v);
    Self(b)
  }
}

impl<'a> ::flatbuffers::Verifiable for EdgeKind {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    u8::run_verifier(v, pos)
  }
}

impl ::flatbuffers::SimpleToVerifyInSlice for EdgeKind {}
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MIN_TYPE: u8 = 0;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MAX_TYPE: u8 = 8;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
#[allow(non_camel_case_types)]
pub const ENUM_VALUES_TYPE: [Type; 9] = [
  Type::Unspecified,
  Type::Int,
  Type::Float,
  Type::String,
  Type::Bool,
  Type::Null,
  Type::Any,
  Type::List,
  Type::Map,
];

#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Default)]
#[repr(transparent)]
pub struct Type(pub u8);
#[allow(non_upper_case_globals)]
impl Type {
  pub const Unspecified: Self = Self(0);
  pub const Int: Self = Self(1);
  pub const Float: Self = Self(2);
  pub const String: Self = Self(3);
  pub const Bool: Self = Self(4);
  pub const Null: Self = Self(5);
  pub const Any: Self = Self(6);
  pub const List: Self = Self(7);
  pub const Map: Self = Self(8);

  pub const ENUM_MIN: u8 = 0;
  pub const ENUM_MAX: u8 = 8;
  pub const ENUM_VALUES: &'static [Self] = &[
    Self::Unspecified,
    Self::Int,
    Self::Float,
    Self::String,
    Self::Bool,
    Self::Null,
    Self::Any,
    Self::List,
    Self::Map,
  ];
  /// Returns the variant's name or "" if unknown.
  pub fn variant_name(self) -> Option<&'static str> {
    match self {
      Self::Unspecified => Some("Unspecified"),
      Self::Int => Some("Int"),
      Self::Float => Some("Float"),
      Self::String => Some("String"),
      Self::Bool => Some("Bool"),
      Self::Null => Some("Null"),
      Self::Any => Some("Any"),
      Self::List => Some("List"),
      Self::Map => Some("Map"),
      _ => None,
    }
  }
}
impl ::core::fmt::Debug for Type {
  fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
    if let Some(name) = self.variant_name() {
      f.write_str(name)
    } else {
      f.write_fmt(format_args!("<UNKNOWN {:?}>", self.0))
    }
  }
}
impl<'a> ::flatbuffers::Follow<'a> for Type {
  type Inner = Self;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    let b = unsafe { ::flatbuffers::read_scalar_at::<u8>(buf, loc) };
    Self(b)
  }
}

impl ::flatbuffers::Push for Type {
    type Output = Type;
    #[inline]
    unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
        unsafe { ::flatbuffers::emplace_scalar::<u8>(dst, self.0) };
    }
}

impl ::flatbuffers::EndianScalar for Type {
  type Scalar = u8;
  #[inline]
  fn to_little_endian(self) -> u8 {
    self.0.to_le()
  }
  #[inline]
  #[allow(clippy::wrong_self_convention)]
  fn from_little_endian(v: u8) -> Self {
    let b = u8::from_le(v);
    Self(b)
  }
}

impl<'a> ::flatbuffers::Verifiable for Type {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    u8::run_verifier(v, pos)
  }
}

impl ::flatbuffers::SimpleToVerifyInSlice for Type {}
pub enum CompiledArgOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct CompiledArg<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for CompiledArg<'a> {
  type Inner = CompiledArg<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> CompiledArg<'a> {
  pub const VT_KEY: ::flatbuffers::VOffsetT = 4;
  pub const VT_VALUE: ::flatbuffers::VOffsetT = 6;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    CompiledArg { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args CompiledArgArgs<'args>
  ) -> ::flatbuffers::WIPOffset<CompiledArg<'bldr>> {
    let mut builder = CompiledArgBuilder::new(_fbb);
    if let Some(x) = args.value { builder.add_value(x); }
    if let Some(x) = args.key { builder.add_key(x); }
    builder.finish()
  }


  #[inline]
  pub fn key(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(CompiledArg::VT_KEY, None)}
  }
  #[inline]
  pub fn value(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(CompiledArg::VT_VALUE, None)}
  }
}

impl ::flatbuffers::Verifiable for CompiledArg<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("key", Self::VT_KEY, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("value", Self::VT_VALUE, false)?
     .finish();
    Ok(())
  }
}
pub struct CompiledArgArgs<'a> {
    pub key: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub value: Option<::flatbuffers::WIPOffset<&'a str>>,
}
impl<'a> Default for CompiledArgArgs<'a> {
  #[inline]
  fn default() -> Self {
    CompiledArgArgs {
      key: None,
      value: None,
    }
  }
}

pub struct CompiledArgBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> CompiledArgBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_key(&mut self, key: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(CompiledArg::VT_KEY, key);
  }
  #[inline]
  pub fn add_value(&mut self, value: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(CompiledArg::VT_VALUE, value);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> CompiledArgBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    CompiledArgBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<CompiledArg<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for CompiledArg<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("CompiledArg");
      ds.field("key", &self.key());
      ds.field("value", &self.value());
      ds.finish()
  }
}
pub enum MappingEntryOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct MappingEntry<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for MappingEntry<'a> {
  type Inner = MappingEntry<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> MappingEntry<'a> {
  pub const VT_FROM: ::flatbuffers::VOffsetT = 4;
  pub const VT_TO: ::flatbuffers::VOffsetT = 6;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    MappingEntry { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args MappingEntryArgs<'args>
  ) -> ::flatbuffers::WIPOffset<MappingEntry<'bldr>> {
    let mut builder = MappingEntryBuilder::new(_fbb);
    if let Some(x) = args.to { builder.add_to(x); }
    if let Some(x) = args.from { builder.add_from(x); }
    builder.finish()
  }


  #[inline]
  pub fn from(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(MappingEntry::VT_FROM, None)}
  }
  #[inline]
  pub fn to(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(MappingEntry::VT_TO, None)}
  }
}

impl ::flatbuffers::Verifiable for MappingEntry<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("from", Self::VT_FROM, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("to", Self::VT_TO, false)?
     .finish();
    Ok(())
  }
}
pub struct MappingEntryArgs<'a> {
    pub from: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub to: Option<::flatbuffers::WIPOffset<&'a str>>,
}
impl<'a> Default for MappingEntryArgs<'a> {
  #[inline]
  fn default() -> Self {
    MappingEntryArgs {
      from: None,
      to: None,
    }
  }
}

pub struct MappingEntryBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> MappingEntryBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_from(&mut self, from: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(MappingEntry::VT_FROM, from);
  }
  #[inline]
  pub fn add_to(&mut self, to: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(MappingEntry::VT_TO, to);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> MappingEntryBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    MappingEntryBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<MappingEntry<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for MappingEntry<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("MappingEntry");
      ds.field("from", &self.from());
      ds.field("to", &self.to());
      ds.finish()
  }
}
pub enum IdEntryOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct IdEntry<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for IdEntry<'a> {
  type Inner = IdEntry<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> IdEntry<'a> {
  pub const VT_ID: ::flatbuffers::VOffsetT = 4;
  pub const VT_INDEX: ::flatbuffers::VOffsetT = 6;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    IdEntry { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args IdEntryArgs<'args>
  ) -> ::flatbuffers::WIPOffset<IdEntry<'bldr>> {
    let mut builder = IdEntryBuilder::new(_fbb);
    builder.add_index(args.index);
    if let Some(x) = args.id { builder.add_id(x); }
    builder.finish()
  }


  #[inline]
  pub fn id(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(IdEntry::VT_ID, None)}
  }
  #[inline]
  pub fn index(&self) -> u32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u32>(IdEntry::VT_INDEX, Some(0)).unwrap()}
  }
}

impl ::flatbuffers::Verifiable for IdEntry<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("id", Self::VT_ID, false)?
     .visit_field::<u32>("index", Self::VT_INDEX, false)?
     .finish();
    Ok(())
  }
}
pub struct IdEntryArgs<'a> {
    pub id: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub index: u32,
}
impl<'a> Default for IdEntryArgs<'a> {
  #[inline]
  fn default() -> Self {
    IdEntryArgs {
      id: None,
      index: 0,
    }
  }
}

pub struct IdEntryBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> IdEntryBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_id(&mut self, id: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(IdEntry::VT_ID, id);
  }
  #[inline]
  pub fn add_index(&mut self, index: u32) {
    self.fbb_.push_slot::<u32>(IdEntry::VT_INDEX, index, 0);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> IdEntryBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    IdEntryBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<IdEntry<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for IdEntry<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("IdEntry");
      ds.field("id", &self.id());
      ds.field("index", &self.index());
      ds.finish()
  }
}
pub enum ToolDepOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct ToolDep<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for ToolDep<'a> {
  type Inner = ToolDep<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> ToolDep<'a> {
  pub const VT_NAME: ::flatbuffers::VOffsetT = 4;
  pub const VT_VERSION: ::flatbuffers::VOffsetT = 6;
  pub const VT_PURE_: ::flatbuffers::VOffsetT = 8;
  pub const VT_SCHEMA_HASH: ::flatbuffers::VOffsetT = 10;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    ToolDep { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args ToolDepArgs<'args>
  ) -> ::flatbuffers::WIPOffset<ToolDep<'bldr>> {
    let mut builder = ToolDepBuilder::new(_fbb);
    if let Some(x) = args.schema_hash { builder.add_schema_hash(x); }
    if let Some(x) = args.version { builder.add_version(x); }
    if let Some(x) = args.name { builder.add_name(x); }
    builder.add_pure_(args.pure_);
    builder.finish()
  }


  #[inline]
  pub fn name(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(ToolDep::VT_NAME, None)}
  }
  #[inline]
  pub fn version(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(ToolDep::VT_VERSION, None)}
  }
  #[inline]
  pub fn pure_(&self) -> bool {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<bool>(ToolDep::VT_PURE_, Some(false)).unwrap()}
  }
  #[inline]
  pub fn schema_hash(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(ToolDep::VT_SCHEMA_HASH, None)}
  }
}

impl ::flatbuffers::Verifiable for ToolDep<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("name", Self::VT_NAME, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("version", Self::VT_VERSION, false)?
     .visit_field::<bool>("pure_", Self::VT_PURE_, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("schema_hash", Self::VT_SCHEMA_HASH, false)?
     .finish();
    Ok(())
  }
}
pub struct ToolDepArgs<'a> {
    pub name: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub version: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub pure_: bool,
    pub schema_hash: Option<::flatbuffers::WIPOffset<&'a str>>,
}
impl<'a> Default for ToolDepArgs<'a> {
  #[inline]
  fn default() -> Self {
    ToolDepArgs {
      name: None,
      version: None,
      pure_: false,
      schema_hash: None,
    }
  }
}

pub struct ToolDepBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> ToolDepBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_name(&mut self, name: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(ToolDep::VT_NAME, name);
  }
  #[inline]
  pub fn add_version(&mut self, version: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(ToolDep::VT_VERSION, version);
  }
  #[inline]
  pub fn add_pure_(&mut self, pure_: bool) {
    self.fbb_.push_slot::<bool>(ToolDep::VT_PURE_, pure_, false);
  }
  #[inline]
  pub fn add_schema_hash(&mut self, schema_hash: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(ToolDep::VT_SCHEMA_HASH, schema_hash);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> ToolDepBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    ToolDepBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<ToolDep<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for ToolDep<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("ToolDep");
      ds.field("name", &self.name());
      ds.field("version", &self.version());
      ds.field("pure_", &self.pure_());
      ds.field("schema_hash", &self.schema_hash());
      ds.finish()
  }
}
pub enum CompiledNodeOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct CompiledNode<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for CompiledNode<'a> {
  type Inner = CompiledNode<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> CompiledNode<'a> {
  pub const VT_INDEX: ::flatbuffers::VOffsetT = 4;
  pub const VT_ID: ::flatbuffers::VOffsetT = 6;
  pub const VT_OP: ::flatbuffers::VOffsetT = 8;
  pub const VT_ARGS: ::flatbuffers::VOffsetT = 10;
  pub const VT_INFERRED_TYPE: ::flatbuffers::VOffsetT = 12;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    CompiledNode { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args CompiledNodeArgs<'args>
  ) -> ::flatbuffers::WIPOffset<CompiledNode<'bldr>> {
    let mut builder = CompiledNodeBuilder::new(_fbb);
    if let Some(x) = args.args { builder.add_args(x); }
    if let Some(x) = args.id { builder.add_id(x); }
    builder.add_index(args.index);
    builder.add_inferred_type(args.inferred_type);
    builder.add_op(args.op);
    builder.finish()
  }


  #[inline]
  pub fn index(&self) -> u32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u32>(CompiledNode::VT_INDEX, Some(0)).unwrap()}
  }
  #[inline]
  pub fn id(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(CompiledNode::VT_ID, None)}
  }
  #[inline]
  pub fn op(&self) -> Opcode {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<Opcode>(CompiledNode::VT_OP, Some(Opcode::Input)).unwrap()}
  }
  #[inline]
  pub fn args(&self) -> Option<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<CompiledArg<'a>>>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<CompiledArg>>>>(CompiledNode::VT_ARGS, None)}
  }
  #[inline]
  pub fn inferred_type(&self) -> Type {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<Type>(CompiledNode::VT_INFERRED_TYPE, Some(Type::Unspecified)).unwrap()}
  }
}

impl ::flatbuffers::Verifiable for CompiledNode<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<u32>("index", Self::VT_INDEX, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("id", Self::VT_ID, false)?
     .visit_field::<Opcode>("op", Self::VT_OP, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, ::flatbuffers::ForwardsUOffset<CompiledArg>>>>("args", Self::VT_ARGS, false)?
     .visit_field::<Type>("inferred_type", Self::VT_INFERRED_TYPE, false)?
     .finish();
    Ok(())
  }
}
pub struct CompiledNodeArgs<'a> {
    pub index: u32,
    pub id: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub op: Opcode,
    pub args: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<CompiledArg<'a>>>>>,
    pub inferred_type: Type,
}
impl<'a> Default for CompiledNodeArgs<'a> {
  #[inline]
  fn default() -> Self {
    CompiledNodeArgs {
      index: 0,
      id: None,
      op: Opcode::Input,
      args: None,
      inferred_type: Type::Unspecified,
    }
  }
}

pub struct CompiledNodeBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> CompiledNodeBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_index(&mut self, index: u32) {
    self.fbb_.push_slot::<u32>(CompiledNode::VT_INDEX, index, 0);
  }
  #[inline]
  pub fn add_id(&mut self, id: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(CompiledNode::VT_ID, id);
  }
  #[inline]
  pub fn add_op(&mut self, op: Opcode) {
    self.fbb_.push_slot::<Opcode>(CompiledNode::VT_OP, op, Opcode::Input);
  }
  #[inline]
  pub fn add_args(&mut self, args: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , ::flatbuffers::ForwardsUOffset<CompiledArg<'b >>>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(CompiledNode::VT_ARGS, args);
  }
  #[inline]
  pub fn add_inferred_type(&mut self, inferred_type: Type) {
    self.fbb_.push_slot::<Type>(CompiledNode::VT_INFERRED_TYPE, inferred_type, Type::Unspecified);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> CompiledNodeBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    CompiledNodeBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<CompiledNode<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for CompiledNode<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("CompiledNode");
      ds.field("index", &self.index());
      ds.field("id", &self.id());
      ds.field("op", &self.op());
      ds.field("args", &self.args());
      ds.field("inferred_type", &self.inferred_type());
      ds.finish()
  }
}
pub enum CompiledEdgeOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct CompiledEdge<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for CompiledEdge<'a> {
  type Inner = CompiledEdge<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> CompiledEdge<'a> {
  pub const VT_FROM_INDEX: ::flatbuffers::VOffsetT = 4;
  pub const VT_TO_INDEX: ::flatbuffers::VOffsetT = 6;
  pub const VT_CONDITION: ::flatbuffers::VOffsetT = 8;
  pub const VT_MAPPING: ::flatbuffers::VOffsetT = 10;
  pub const VT_PRIORITY: ::flatbuffers::VOffsetT = 12;
  pub const VT_LABEL: ::flatbuffers::VOffsetT = 14;
  pub const VT_KIND: ::flatbuffers::VOffsetT = 16;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    CompiledEdge { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args CompiledEdgeArgs<'args>
  ) -> ::flatbuffers::WIPOffset<CompiledEdge<'bldr>> {
    let mut builder = CompiledEdgeBuilder::new(_fbb);
    if let Some(x) = args.label { builder.add_label(x); }
    builder.add_priority(args.priority);
    if let Some(x) = args.mapping { builder.add_mapping(x); }
    if let Some(x) = args.condition { builder.add_condition(x); }
    builder.add_to_index(args.to_index);
    builder.add_from_index(args.from_index);
    builder.add_kind(args.kind);
    builder.finish()
  }


  #[inline]
  pub fn from_index(&self) -> u32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u32>(CompiledEdge::VT_FROM_INDEX, Some(0)).unwrap()}
  }
  #[inline]
  pub fn to_index(&self) -> u32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u32>(CompiledEdge::VT_TO_INDEX, Some(0)).unwrap()}
  }
  #[inline]
  pub fn condition(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(CompiledEdge::VT_CONDITION, None)}
  }
  #[inline]
  pub fn mapping(&self) -> Option<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<MappingEntry<'a>>>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<MappingEntry>>>>(CompiledEdge::VT_MAPPING, None)}
  }
  #[inline]
  pub fn priority(&self) -> i32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<i32>(CompiledEdge::VT_PRIORITY, Some(0)).unwrap()}
  }
  #[inline]
  pub fn label(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(CompiledEdge::VT_LABEL, None)}
  }
  #[inline]
  pub fn kind(&self) -> EdgeKind {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<EdgeKind>(CompiledEdge::VT_KIND, Some(EdgeKind::EK_Data)).unwrap()}
  }
}

impl ::flatbuffers::Verifiable for CompiledEdge<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<u32>("from_index", Self::VT_FROM_INDEX, false)?
     .visit_field::<u32>("to_index", Self::VT_TO_INDEX, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("condition", Self::VT_CONDITION, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, ::flatbuffers::ForwardsUOffset<MappingEntry>>>>("mapping", Self::VT_MAPPING, false)?
     .visit_field::<i32>("priority", Self::VT_PRIORITY, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("label", Self::VT_LABEL, false)?
     .visit_field::<EdgeKind>("kind", Self::VT_KIND, false)?
     .finish();
    Ok(())
  }
}
pub struct CompiledEdgeArgs<'a> {
    pub from_index: u32,
    pub to_index: u32,
    pub condition: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub mapping: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<MappingEntry<'a>>>>>,
    pub priority: i32,
    pub label: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub kind: EdgeKind,
}
impl<'a> Default for CompiledEdgeArgs<'a> {
  #[inline]
  fn default() -> Self {
    CompiledEdgeArgs {
      from_index: 0,
      to_index: 0,
      condition: None,
      mapping: None,
      priority: 0,
      label: None,
      kind: EdgeKind::EK_Data,
    }
  }
}

pub struct CompiledEdgeBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> CompiledEdgeBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_from_index(&mut self, from_index: u32) {
    self.fbb_.push_slot::<u32>(CompiledEdge::VT_FROM_INDEX, from_index, 0);
  }
  #[inline]
  pub fn add_to_index(&mut self, to_index: u32) {
    self.fbb_.push_slot::<u32>(CompiledEdge::VT_TO_INDEX, to_index, 0);
  }
  #[inline]
  pub fn add_condition(&mut self, condition: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(CompiledEdge::VT_CONDITION, condition);
  }
  #[inline]
  pub fn add_mapping(&mut self, mapping: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , ::flatbuffers::ForwardsUOffset<MappingEntry<'b >>>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(CompiledEdge::VT_MAPPING, mapping);
  }
  #[inline]
  pub fn add_priority(&mut self, priority: i32) {
    self.fbb_.push_slot::<i32>(CompiledEdge::VT_PRIORITY, priority, 0);
  }
  #[inline]
  pub fn add_label(&mut self, label: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(CompiledEdge::VT_LABEL, label);
  }
  #[inline]
  pub fn add_kind(&mut self, kind: EdgeKind) {
    self.fbb_.push_slot::<EdgeKind>(CompiledEdge::VT_KIND, kind, EdgeKind::EK_Data);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> CompiledEdgeBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    CompiledEdgeBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<CompiledEdge<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for CompiledEdge<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("CompiledEdge");
      ds.field("from_index", &self.from_index());
      ds.field("to_index", &self.to_index());
      ds.field("condition", &self.condition());
      ds.field("mapping", &self.mapping());
      ds.field("priority", &self.priority());
      ds.field("label", &self.label());
      ds.field("kind", &self.kind());
      ds.finish()
  }
}
pub enum CompiledMetadataOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct CompiledMetadata<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for CompiledMetadata<'a> {
  type Inner = CompiledMetadata<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> CompiledMetadata<'a> {
  pub const VT_COMPILER_VERSION: ::flatbuffers::VOffsetT = 4;
  pub const VT_COMPILED_AT: ::flatbuffers::VOffsetT = 6;
  pub const VT_NODE_COUNT: ::flatbuffers::VOffsetT = 8;
  pub const VT_EDGE_COUNT: ::flatbuffers::VOffsetT = 10;
  pub const VT_MAX_NODE_EXECUTION_COUNT: ::flatbuffers::VOffsetT = 12;
  pub const VT_MAX_CONTEXT_MEMORY_BYTES: ::flatbuffers::VOffsetT = 14;
  pub const VT_MAX_RECURSION_DEPTH: ::flatbuffers::VOffsetT = 16;
  pub const VT_MAX_EXECUTION_TIME_MS: ::flatbuffers::VOffsetT = 18;
  pub const VT_OPTIMIZATIONS: ::flatbuffers::VOffsetT = 20;
  pub const VT_TOOL_DEPS: ::flatbuffers::VOffsetT = 22;
  pub const VT_SUBGRAPH_DEPENDENCIES: ::flatbuffers::VOffsetT = 24;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    CompiledMetadata { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args CompiledMetadataArgs<'args>
  ) -> ::flatbuffers::WIPOffset<CompiledMetadata<'bldr>> {
    let mut builder = CompiledMetadataBuilder::new(_fbb);
    if let Some(x) = args.subgraph_dependencies { builder.add_subgraph_dependencies(x); }
    if let Some(x) = args.tool_deps { builder.add_tool_deps(x); }
    if let Some(x) = args.optimizations { builder.add_optimizations(x); }
    builder.add_max_execution_time_ms(args.max_execution_time_ms);
    builder.add_max_recursion_depth(args.max_recursion_depth);
    builder.add_max_context_memory_bytes(args.max_context_memory_bytes);
    builder.add_max_node_execution_count(args.max_node_execution_count);
    builder.add_edge_count(args.edge_count);
    builder.add_node_count(args.node_count);
    if let Some(x) = args.compiled_at { builder.add_compiled_at(x); }
    if let Some(x) = args.compiler_version { builder.add_compiler_version(x); }
    builder.finish()
  }


  #[inline]
  pub fn compiler_version(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(CompiledMetadata::VT_COMPILER_VERSION, None)}
  }
  #[inline]
  pub fn compiled_at(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(CompiledMetadata::VT_COMPILED_AT, None)}
  }
  #[inline]
  pub fn node_count(&self) -> u32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u32>(CompiledMetadata::VT_NODE_COUNT, Some(0)).unwrap()}
  }
  #[inline]
  pub fn edge_count(&self) -> u32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u32>(CompiledMetadata::VT_EDGE_COUNT, Some(0)).unwrap()}
  }
  #[inline]
  pub fn max_node_execution_count(&self) -> u32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u32>(CompiledMetadata::VT_MAX_NODE_EXECUTION_COUNT, Some(10000)).unwrap()}
  }
  #[inline]
  pub fn max_context_memory_bytes(&self) -> u32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u32>(CompiledMetadata::VT_MAX_CONTEXT_MEMORY_BYTES, Some(10485760)).unwrap()}
  }
  #[inline]
  pub fn max_recursion_depth(&self) -> u32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u32>(CompiledMetadata::VT_MAX_RECURSION_DEPTH, Some(5)).unwrap()}
  }
  #[inline]
  pub fn max_execution_time_ms(&self) -> u32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u32>(CompiledMetadata::VT_MAX_EXECUTION_TIME_MS, Some(30000)).unwrap()}
  }
  #[inline]
  pub fn optimizations(&self) -> Option<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<&'a str>>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<&'a str>>>>(CompiledMetadata::VT_OPTIMIZATIONS, None)}
  }
  #[inline]
  pub fn tool_deps(&self) -> Option<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<ToolDep<'a>>>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<ToolDep>>>>(CompiledMetadata::VT_TOOL_DEPS, None)}
  }
  #[inline]
  pub fn subgraph_dependencies(&self) -> Option<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<&'a str>>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<&'a str>>>>(CompiledMetadata::VT_SUBGRAPH_DEPENDENCIES, None)}
  }
}

impl ::flatbuffers::Verifiable for CompiledMetadata<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("compiler_version", Self::VT_COMPILER_VERSION, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("compiled_at", Self::VT_COMPILED_AT, false)?
     .visit_field::<u32>("node_count", Self::VT_NODE_COUNT, false)?
     .visit_field::<u32>("edge_count", Self::VT_EDGE_COUNT, false)?
     .visit_field::<u32>("max_node_execution_count", Self::VT_MAX_NODE_EXECUTION_COUNT, false)?
     .visit_field::<u32>("max_context_memory_bytes", Self::VT_MAX_CONTEXT_MEMORY_BYTES, false)?
     .visit_field::<u32>("max_recursion_depth", Self::VT_MAX_RECURSION_DEPTH, false)?
     .visit_field::<u32>("max_execution_time_ms", Self::VT_MAX_EXECUTION_TIME_MS, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, ::flatbuffers::ForwardsUOffset<&'_ str>>>>("optimizations", Self::VT_OPTIMIZATIONS, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, ::flatbuffers::ForwardsUOffset<ToolDep>>>>("tool_deps", Self::VT_TOOL_DEPS, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, ::flatbuffers::ForwardsUOffset<&'_ str>>>>("subgraph_dependencies", Self::VT_SUBGRAPH_DEPENDENCIES, false)?
     .finish();
    Ok(())
  }
}
pub struct CompiledMetadataArgs<'a> {
    pub compiler_version: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub compiled_at: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub node_count: u32,
    pub edge_count: u32,
    pub max_node_execution_count: u32,
    pub max_context_memory_bytes: u32,
    pub max_recursion_depth: u32,
    pub max_execution_time_ms: u32,
    pub optimizations: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<&'a str>>>>,
    pub tool_deps: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<ToolDep<'a>>>>>,
    pub subgraph_dependencies: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<&'a str>>>>,
}
impl<'a> Default for CompiledMetadataArgs<'a> {
  #[inline]
  fn default() -> Self {
    CompiledMetadataArgs {
      compiler_version: None,
      compiled_at: None,
      node_count: 0,
      edge_count: 0,
      max_node_execution_count: 10000,
      max_context_memory_bytes: 10485760,
      max_recursion_depth: 5,
      max_execution_time_ms: 30000,
      optimizations: None,
      tool_deps: None,
      subgraph_dependencies: None,
    }
  }
}

pub struct CompiledMetadataBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> CompiledMetadataBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_compiler_version(&mut self, compiler_version: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(CompiledMetadata::VT_COMPILER_VERSION, compiler_version);
  }
  #[inline]
  pub fn add_compiled_at(&mut self, compiled_at: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(CompiledMetadata::VT_COMPILED_AT, compiled_at);
  }
  #[inline]
  pub fn add_node_count(&mut self, node_count: u32) {
    self.fbb_.push_slot::<u32>(CompiledMetadata::VT_NODE_COUNT, node_count, 0);
  }
  #[inline]
  pub fn add_edge_count(&mut self, edge_count: u32) {
    self.fbb_.push_slot::<u32>(CompiledMetadata::VT_EDGE_COUNT, edge_count, 0);
  }
  #[inline]
  pub fn add_max_node_execution_count(&mut self, max_node_execution_count: u32) {
    self.fbb_.push_slot::<u32>(CompiledMetadata::VT_MAX_NODE_EXECUTION_COUNT, max_node_execution_count, 10000);
  }
  #[inline]
  pub fn add_max_context_memory_bytes(&mut self, max_context_memory_bytes: u32) {
    self.fbb_.push_slot::<u32>(CompiledMetadata::VT_MAX_CONTEXT_MEMORY_BYTES, max_context_memory_bytes, 10485760);
  }
  #[inline]
  pub fn add_max_recursion_depth(&mut self, max_recursion_depth: u32) {
    self.fbb_.push_slot::<u32>(CompiledMetadata::VT_MAX_RECURSION_DEPTH, max_recursion_depth, 5);
  }
  #[inline]
  pub fn add_max_execution_time_ms(&mut self, max_execution_time_ms: u32) {
    self.fbb_.push_slot::<u32>(CompiledMetadata::VT_MAX_EXECUTION_TIME_MS, max_execution_time_ms, 30000);
  }
  #[inline]
  pub fn add_optimizations(&mut self, optimizations: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , ::flatbuffers::ForwardsUOffset<&'b  str>>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(CompiledMetadata::VT_OPTIMIZATIONS, optimizations);
  }
  #[inline]
  pub fn add_tool_deps(&mut self, tool_deps: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , ::flatbuffers::ForwardsUOffset<ToolDep<'b >>>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(CompiledMetadata::VT_TOOL_DEPS, tool_deps);
  }
  #[inline]
  pub fn add_subgraph_dependencies(&mut self, subgraph_dependencies: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , ::flatbuffers::ForwardsUOffset<&'b  str>>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(CompiledMetadata::VT_SUBGRAPH_DEPENDENCIES, subgraph_dependencies);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> CompiledMetadataBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    CompiledMetadataBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<CompiledMetadata<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for CompiledMetadata<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("CompiledMetadata");
      ds.field("compiler_version", &self.compiler_version());
      ds.field("compiled_at", &self.compiled_at());
      ds.field("node_count", &self.node_count());
      ds.field("edge_count", &self.edge_count());
      ds.field("max_node_execution_count", &self.max_node_execution_count());
      ds.field("max_context_memory_bytes", &self.max_context_memory_bytes());
      ds.field("max_recursion_depth", &self.max_recursion_depth());
      ds.field("max_execution_time_ms", &self.max_execution_time_ms());
      ds.field("optimizations", &self.optimizations());
      ds.field("tool_deps", &self.tool_deps());
      ds.field("subgraph_dependencies", &self.subgraph_dependencies());
      ds.finish()
  }
}
pub enum ExecutionPlanOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct ExecutionPlan<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for ExecutionPlan<'a> {
  type Inner = ExecutionPlan<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> ExecutionPlan<'a> {
  pub const VT_VERSION: ::flatbuffers::VOffsetT = 4;
  pub const VT_NODES: ::flatbuffers::VOffsetT = 6;
  pub const VT_EDGES: ::flatbuffers::VOffsetT = 8;
  pub const VT_METADATA: ::flatbuffers::VOffsetT = 10;
  pub const VT_ID_MAP: ::flatbuffers::VOffsetT = 12;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    ExecutionPlan { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args ExecutionPlanArgs<'args>
  ) -> ::flatbuffers::WIPOffset<ExecutionPlan<'bldr>> {
    let mut builder = ExecutionPlanBuilder::new(_fbb);
    if let Some(x) = args.id_map { builder.add_id_map(x); }
    if let Some(x) = args.metadata { builder.add_metadata(x); }
    if let Some(x) = args.edges { builder.add_edges(x); }
    if let Some(x) = args.nodes { builder.add_nodes(x); }
    builder.add_version(args.version);
    builder.finish()
  }


  #[inline]
  pub fn version(&self) -> u16 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u16>(ExecutionPlan::VT_VERSION, Some(2)).unwrap()}
  }
  #[inline]
  pub fn nodes(&self) -> Option<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<CompiledNode<'a>>>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<CompiledNode>>>>(ExecutionPlan::VT_NODES, None)}
  }
  #[inline]
  pub fn edges(&self) -> Option<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<CompiledEdge<'a>>>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<CompiledEdge>>>>(ExecutionPlan::VT_EDGES, None)}
  }
  #[inline]
  pub fn metadata(&self) -> Option<CompiledMetadata<'a>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<CompiledMetadata>>(ExecutionPlan::VT_METADATA, None)}
  }
  #[inline]
  pub fn id_map(&self) -> Option<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<IdEntry<'a>>>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<IdEntry>>>>(ExecutionPlan::VT_ID_MAP, None)}
  }
}

impl ::flatbuffers::Verifiable for ExecutionPlan<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<u16>("version", Self::VT_VERSION, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, ::flatbuffers::ForwardsUOffset<CompiledNode>>>>("nodes", Self::VT_NODES, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, ::flatbuffers::ForwardsUOffset<CompiledEdge>>>>("edges", Self::VT_EDGES, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<CompiledMetadata>>("metadata", Self::VT_METADATA, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, ::flatbuffers::ForwardsUOffset<IdEntry>>>>("id_map", Self::VT_ID_MAP, false)?
     .finish();
    Ok(())
  }
}
pub struct ExecutionPlanArgs<'a> {
    pub version: u16,
    pub nodes: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<CompiledNode<'a>>>>>,
    pub edges: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<CompiledEdge<'a>>>>>,
    pub metadata: Option<::flatbuffers::WIPOffset<CompiledMetadata<'a>>>,
    pub id_map: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<IdEntry<'a>>>>>,
}
impl<'a> Default for ExecutionPlanArgs<'a> {
  #[inline]
  fn default() -> Self {
    ExecutionPlanArgs {
      version: 2,
      nodes: None,
      edges: None,
      metadata: None,
      id_map: None,
    }
  }
}

pub struct ExecutionPlanBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> ExecutionPlanBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_version(&mut self, version: u16) {
    self.fbb_.push_slot::<u16>(ExecutionPlan::VT_VERSION, version, 2);
  }
  #[inline]
  pub fn add_nodes(&mut self, nodes: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , ::flatbuffers::ForwardsUOffset<CompiledNode<'b >>>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(ExecutionPlan::VT_NODES, nodes);
  }
  #[inline]
  pub fn add_edges(&mut self, edges: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , ::flatbuffers::ForwardsUOffset<CompiledEdge<'b >>>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(ExecutionPlan::VT_EDGES, edges);
  }
  #[inline]
  pub fn add_metadata(&mut self, metadata: ::flatbuffers::WIPOffset<CompiledMetadata<'b >>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<CompiledMetadata>>(ExecutionPlan::VT_METADATA, metadata);
  }
  #[inline]
  pub fn add_id_map(&mut self, id_map: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , ::flatbuffers::ForwardsUOffset<IdEntry<'b >>>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(ExecutionPlan::VT_ID_MAP, id_map);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> ExecutionPlanBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    ExecutionPlanBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<ExecutionPlan<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for ExecutionPlan<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("ExecutionPlan");
      ds.field("version", &self.version());
      ds.field("nodes", &self.nodes());
      ds.field("edges", &self.edges());
      ds.field("metadata", &self.metadata());
      ds.field("id_map", &self.id_map());
      ds.finish()
  }
}
#[inline]
/// Verifies that a buffer of bytes contains a `ExecutionPlan`
/// and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_execution_plan_unchecked`.
pub fn root_as_execution_plan(buf: &[u8]) -> Result<ExecutionPlan<'_>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::root::<ExecutionPlan>(buf)
}
#[inline]
/// Verifies that a buffer of bytes contains a size prefixed
/// `ExecutionPlan` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `size_prefixed_root_as_execution_plan_unchecked`.
pub fn size_prefixed_root_as_execution_plan(buf: &[u8]) -> Result<ExecutionPlan<'_>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::size_prefixed_root::<ExecutionPlan>(buf)
}
#[inline]
/// Verifies, with the given options, that a buffer of bytes
/// contains a `ExecutionPlan` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_execution_plan_unchecked`.
pub fn root_as_execution_plan_with_opts<'b, 'o>(
  opts: &'o ::flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<ExecutionPlan<'b>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::root_with_opts::<ExecutionPlan<'b>>(opts, buf)
}
#[inline]
/// Verifies, with the given verifier options, that a buffer of
/// bytes contains a size prefixed `ExecutionPlan` and returns
/// it. Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_execution_plan_unchecked`.
pub fn size_prefixed_root_as_execution_plan_with_opts<'b, 'o>(
  opts: &'o ::flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<ExecutionPlan<'b>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::size_prefixed_root_with_opts::<ExecutionPlan<'b>>(opts, buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a ExecutionPlan and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid `ExecutionPlan`.
pub unsafe fn root_as_execution_plan_unchecked(buf: &[u8]) -> ExecutionPlan<'_> {
  unsafe { ::flatbuffers::root_unchecked::<ExecutionPlan>(buf) }
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a size prefixed ExecutionPlan and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid size prefixed `ExecutionPlan`.
pub unsafe fn size_prefixed_root_as_execution_plan_unchecked(buf: &[u8]) -> ExecutionPlan<'_> {
  unsafe { ::flatbuffers::size_prefixed_root_unchecked::<ExecutionPlan>(buf) }
}
#[inline]
pub fn finish_execution_plan_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(
    fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
    root: ::flatbuffers::WIPOffset<ExecutionPlan<'a>>) {
  fbb.finish(root, None);
}

#[inline]
pub fn finish_size_prefixed_execution_plan_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>, root: ::flatbuffers::WIPOffset<ExecutionPlan<'a>>) {
  fbb.finish_size_prefixed(root, None);
}
